# This is a basic workflow to help you get started with Actions

name: Upload on Tag

# Controls when the workflow will run
on:
  create:
    tags:
      -'**'
  push:
    tags:
      -'**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload Website files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: spzroenkhausen.bplaced.net
          username: spzroenkhausen_admin
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: ./www/
