# This is a basic workflow to help you get started with Actions

name: Daily Upload

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Upload
        run: echo Upload files to Server
