# This is a basic workflow to help you get started with Actions

name: Upload on Tag

# Controls when the workflow will run
on:
  create:
    tags:
      -'v[0-9].*.*'
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'tag'
    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.get_tag_name.outputs.VERSION }}
      - name: Upload Website files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: spzroenkhausen.bplaced.net
          username: spzroenkhausen_admin
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./api/
          server-dir: ./www/api/
